### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by jm3** [jacobSingh/tabwrangler#100]
Hi, just curious: looks like the last commit was about five months ago — is this extension still being maintained?

**Comment by ssorallen** [comment]
I have been using Tab Wrangler for several years and decided to revive and modernize its codebase. My fork is https://github.com/ssorallen/tabwrangler. It uses React to render instead of jQuery (fixes #101, which was due to the many DOM manipulations), is written ES6 (including for its modules), and linting.

I'm going to see if @jacobSingh is interested in merging it after some review and maybe whether I could become a maintainer. I've read through the open issues and could fix most of them now that I know the codebase. Up to @jacobSingh though!

**Comment by ssorallen** [comment]
@jacobSingh gave me access to both the GitHub repo and to the extension in the Chrome store. I'm claiming maintenance for the foreseeable futures. Send your PRs!

Jacob's repo will still be the canonical source, so I'm watching issues and PRs here.
