### ISSUE TITLE
Change X to checkbox

### ISSUE THREAD

**Issue by eorroe** [jacobSingh/tabwrangler#127]
If the X for deleting a tab was changed to a checkbox, it'll help avoid deleting tabs I actually wanted.

**Comment by ssorallen** [comment]
Agreed. This is similar to #117, which suggested multi-select for the tabs popup. I want it to be a Gmail-style interface for multi-select.

**Comment by jacobSingh** [comment]
Ross! So much ass kicking!

On May 22, 2017 12:42 PM, "Ross Allen" <notifications@github.com> wrote:

Closed #127 <https://github.com/jacobSingh/tabwrangler/issues/127> via #132
<https://github.com/jacobSingh/tabwrangler/pull/132>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jacobSingh/tabwrangler/issues/127#event-1091267251>,
or mute
the thread
