### ISSUE TITLE
Brilliant Todo List Idea for TabWrangler

### ISSUE THREAD

**Issue by eorroe** [jacobSingh/tabwrangler#137]
I still sometimes have problems focusing on one thing because of the right workflow even though I [know about the right tools](https://bold.io/tab-management-2017-05-15)

There are times when I open a new tab to not forget to do something and wait for it to load and end up with too many tabs. Thankfully TabWranlger comes in and rescues me by taking them away. 

I think something interesting would be if there was a shortcut that opened a new tab where I type what I want to do and then by pressing enter it gets wrangled as the next thing to do but reminding me to finish what I need to do and not worry about why I was going to open a new tab after I finish. 

I can then easily open TabWrangler and see what I was going to do next.

I realize the ultimate problem is that we use new tabs as things to do, like a to-do list, and instead of loading the page TabWrangler could store the thing to do. Then when I open it again the to-do shows in fullscreen and I remember the new site I was going to go to and continue from there.

Thanks, very interested on your input

**Comment by ssorallen** [comment]
This sounds like a great idea, and I'd be curious to see an extension that enables a todo list based on tabs. This is beyond the scope of Tab Wrangler at the moment though; TW closes tabs based on a time interval and keeps a list of the tabs it closed. Since I have limited time to continue developing this extension, I'd like to keep its feature set tightly scoped until another volunteer who has more time to devote is able to explore interesting ideas like this one.

I appreciate the issues you open, please keep them coming.

**Comment by eorroe** [comment]
Yea TabSnooze actually does this, but except TabSnooze has a different purpose. I found that having the shortcut to wrangle a tab, sort of does the job. So I don't really mind if this feature is implemented a while from now. I now just make a google search and just wrangle the google search, wrangle it and get back to it later. So honestly not sure if this is even necessary. But glad you like the idea

> I appreciate the issues you open, please keep them coming.

Sure thing
