### ISSUE TITLE
Don't auto-close if I only have X tabs setting does not save "0"

### ISSUE THREAD

**Issue by stevenqzhang** [jacobSingh/tabwrangler#97]
If I set the Don't auto-close if I only have _ tabs setting to 0, it'll default back to 1 the next time I restart chrome

**Comment by jacobSingh** [comment]
Hmm... are you saying you never want it to autoclose?

On Mon, Sep 14, 2015 at 10:52 PM, Steven Zhang <notifications@github.com>
wrote:

> If I set the Don't auto-close if I only have _ tabs setting to 0, it'll
> default back to 1 the next time I restart chrome
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jacobSingh/tabwrangler/issues/97>.
>



-- 
+1 512-522-6281
twitter: @JacobSingh ( http://twitter.com/#!/JacobSingh )
web: http://www.jacobsingh.name
Skype: pajamadesign
gTalk: jacobsingh@gmail.com

**Comment by stevenqzhang** [comment]
Opposite. I want all tabs to be closed if possible. 

With setting set to 1, I often have a bunch of single-tabbed windows at the end of the day. I would prefer not to have that and have the windows closed completely if unused or containing 0 pinned tabs

**Comment by jacobSingh** [comment]
Sorry, that's what I meant, brain a little slow this morning...

Yes, sounds like a bug.
Honestly, I'm not actively maintaining it these days.  If you can patch it,
I'll do a code review, otherwise... not sure when I'll get to it.

Best,
J


On Tue, Sep 15, 2015 at 10:01 AM, Steven Zhang <notifications@github.com>
wrote:

> Opposite. I want all tabs to be closed if possible.
>
> With setting set to 1, I often have a bunch of single-tabbed windows at
> the end of the day. I would prefer not to have that and have the windows
> closed completely if unused or containing 0 pinned tabs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jacobSingh/tabwrangler/issues/97#issuecomment-140277916>
> .
>



-- 
+1 512-522-6281
twitter: @JacobSingh ( http://twitter.com/#!/JacobSingh )
web: http://www.jacobsingh.name
Skype: pajamadesign
gTalk: jacobsingh@gmail.com
